config/routes.rb
Dbproject::Application.routes.draw do
  get "static_pages/home"
  get "static_pages/help"

  resources :sessions, only: [:new, :create, :destroy]

  resources :vendors

  resources :carts

  resources :products

  resources :wishlists

  resources :customers

  root 'static_pages#home'

  match '/customer_signup', to: 'customers#new', via: 'get'
  match '/vendor_signup', to: 'vendors#new',  via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/add_to_cart', to: 'carts#add_to_cart', via: 'get'
  match '/remove_from_cart', to: 'carts#remove_from_cart', via: 'get'
  match '/product_listing', to: 'vendors#product_listing', via: 'get'
  match '/new_product_listing', to: 'vendors#new_product_listing', via: 'get'
  match '/add_random_product', to: 'vendors#add_random_product', via: 'get'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_and_belongs_to_many :products
  belongs_to :customer

  def update_cart
    total = 0
    self.products.each do |product|
      total += product.price
    end
    self.total_price = total
    self.number_of_products = self.products.count
    self.save!
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  def add_to_cart
    @cart = Cart.find_by(id:params[:cart_id])
    if params[:product_id]
      @product = Product.find_by(id:params[:product_id])
      @cart.products << @product
    end
    @cart.update_cart
    render 'show', :cart_id => @cart.id
  end

  def remove_from_cart
    @cart = Cart.find_by(id:params[:cart_id])
    if params[:product_id]
      @product = Product.find_by(id:params[:product_id])
      @cart.products.delete(@product)
    end
    @cart.update_cart
    render 'show', :cart_id => @cart.id
  end

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find_by(id:params[:id])
    @cart.update_cart
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)
    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:customer_id, :number_of_products, :total_price)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.number_field :customer_id %>
  </div>
  <div class="field">
    <%= f.label :number_of_products %><br>
    <%= f.number_field :number_of_products %>
  </div>
  <div class="field">
    <%= f.label :total_price %><br>
    <%= f.text_field :total_price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Number of products</th>
      <th>Total price</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.customer_id %></td>
        <td><%= cart.number_of_products %></td>
        <td><%= cart.total_price %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<div class="container center">
    <div class="jumbotron">
        <p id="notice"><%= notice %></p>

        <p>
          <strong>Customer:</strong>
          <%= Customer.find_by(id: @cart.customer_id).name %>
        </p>
      <table class="table">
        <thead>
        <tr>
          <th><center>Name</center></th>
          <th><center>Price</center></th>
          <th>Quantity</th>
          <th></th>
          <th></th>
        </tr>
        </thead>

        <tbody>
        <% prod_list = @cart.products.all %>
        <% prod_list.uniq.each do |product| %>
            <tr>
              <td><%= link_to product.name, product %></td>
              <td><%= "$%.2f" %product.price %></td>
              <td><%= prod_list.count(product) %></td>
              <td><%= link_to 'Remove from cart', remove_from_cart_path(:cart_id => @cart,:product_id => product.id)%></td>
            </tr>
        <% end %>
        </tbody>
      </table>
        <p>
          <strong>Items in cart:</strong>
          <%= @cart.number_of_products %>
        </p>

        <p>
          <strong>Total:</strong>
          <%= "$%.2f" %@cart.total_price %>
        </p>
        <%= link_to 'Shop', products_path(:cart => @cart), class:'btn btn-default btn-large' %>
    </div>
</div>