config/routes.rb
Dbproject::Application.routes.draw do
  get "static_pages/home"
  get "static_pages/help"

  resources :sessions, only: [:new, :create, :destroy]

  resources :vendors

  resources :carts

  resources :products

  resources :wishlists

  resources :customers

  root 'static_pages#home'

  match '/customer_signup', to: 'customers#new', via: 'get'
  match '/vendor_signup', to: 'vendors#new',  via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/add_to_cart', to: 'carts#add_to_cart', via: 'get'
  match '/remove_from_cart', to: 'carts#remove_from_cart', via: 'get'
  match '/product_listing', to: 'vendors#product_listing', via: 'get'
  match '/new_product_listing', to: 'vendors#new_product_listing', via: 'get'
  match '/add_random_product', to: 'vendors#add_random_product', via: 'get'

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  has_many :sales
  has_many :products

  def add_random_product
    adjectives = ['Obtuse',
                  'Alogical',
                  'Anodyne',
                  'Febrile',
                  'Lurid',
                  'Protuberant',
                  'Redolent',
                  'Preponderant',
                  'Moribund',
                  'Interminable']

    nouns = ['Peck of Frenchmen',
             'Chinese Man',
             'Pumpkin',
             'Basket of Oranges',
             'Interstate Roadsign',
             'Database Systems Textbook',
             'Ouija Board',
             'Satanic Mask',
             'Used Coffin',
             'Can of Pepper Spray',
             'Used Socks',
             'Adult Diapers']

    adjectives.shuffle!
    nouns.shuffle!

    products.create({name:adjectives[0]+" "+nouns[0],
                      price:Random.new.rand(20.0..1500.0),
                      stock:Random.new.rand(10..100),
                      created_at:DateTime.current,
                      updated_at:DateTime.current})
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :edit, :update, :destroy]

  def sign_in
    @vendors = Vendor.all
  end

  def product_listing
    @vendor = Vendor.find_by(:id => params[:vendor_id])
    @products = @vendor.products
  end

  def add_random_product
    @vendor = Vendor.find_by(:id => params[:vendor_id])
    @vendor.add_random_product
    redirect_to :back
  end

  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = Vendor.all
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
    @vendor
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if !Vendor.find_by(username: @vendor.username)
        @vendor.save
        format.html { redirect_to :back, notice: 'Account Successfully Created!' }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      else
        format.html { redirect_to :back, notice: 'User already exists'}
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1
  # PATCH/PUT /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to @vendor, notice: 'Vendor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    Product.delete(@vendor.products)
    @vendor.destroy
    respond_to do |format|
      format.html { redirect_to vendors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendor_params
      params.require(:vendor).permit(:name, :username, :password, :city, :street, :zip, :phone, :created_at, :updated_at)
    end
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.html.erb
<%= form_for(@vendor) do |f| %>
  <% if @vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
      <% @vendor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
      <%= f.label :username %>
      <%= f.text_field :username, class:'form-control', placeholder:'Enter username' %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class:'form-control', placeholder:'Enter password'%>
    </div>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class:'form-control', placeholder:'Enter full name' %>
    </div>
    <div class="form-group">
      <%= f.label :phone %>
      <%= f.text_field :phone, class:'form-control', placeholder:'Enter phone number' %>
    </div>
    <div class="form-group">
      <%= f.label :street %>
      <%= f.text_field :street, class:'form-control', placeholder:'Enter current street address' %>
    </div>
    <div class="form-group">
      <%= f.label :city %>
      <%= f.text_field :city, class:'form-control', placeholder:'Enter current city' %>
    </div>
    <div class="form-group">
      <%= f.label :zip %>
      <%= f.text_field :zip, class:'form-control', placeholder:'Enter zip code' %>
    </div>
    <button type="submit" class="btn btn-default actions">Sign Up</button>
    </form>
<% end %>

app/views/vendors/edit.html.erb
<div class="container center">
  <div class="jumbotron">
    <p id="notice"><%= notice %></p>
    <%= render 'form' %>
  </div>
</div>

app/views/vendors/index.html.erb
<div class="container center">
  <div class="jumbotron">
    <table class="table">
      <thead>
      <tr>
        <th><center>Vendor</center></th>
      </tr>
      </thead>

      <tbody>
      <% @vendors.each do |vendor| %>
          <tr>
            <td><%= link_to  vendor.username, vendor %></td>
            <td><%= link_to 'Edit', edit_vendor_path(vendor) %></td>
            <td><%= link_to 'Destroy', vendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

app/views/vendors/new.html.erb
<div class="container center">
    <div class="jumbotron">
      <p id="notice"><%= notice %></p>
      <%= render 'form' %>
    </div>
</div>

app/views/vendors/product_listing.erb
<div class="container center">
  <div class="jumbotron">
    <table class="table">
      <thead>
      <tr>
        <th><center>Product Name</center></th>
        <th><center>Price</center></th>
        <th><center>Stock</center></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      </thead>

      <tbody>
      <% @products.each do |product| %>
          <tr>
            <td><%= link_to product.name, product %></td>
            <td><%= "$%.2f" % product.price %></td>
            <td><%= product.stock %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <%= link_to 'Add Random Product', add_random_product_path(:vendor_id => @vendor.id), class: 'btn btn-large btn-default'%>
  </div>
</div>
<br>

app/views/vendors/show.html.erb
<div class="container center">
  <div class="jumbotron">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Name:</strong>
      <%= @vendor.name %>
    </p>

    <p>
      <strong>Username:</strong>
      <%= @vendor.username %>
    </p>

    <p>
      <strong>City:</strong>
      <%= @vendor.city %>
    </p>

    <p>
      <strong>Street:</strong>
      <%= @vendor.street %>
    </p>

    <p>
      <strong>Zip:</strong>
      <%= "%05d" % @vendor.zip %>
    </p>

    <p>
      <strong>Phone:</strong>
      <%= @vendor.phone %>
    </p>
    <%= link_to 'View Products', product_listing_path(:vendor_id => @vendor.id), class:'btn btn-default btn-large' %>
  </div>
</div>

app/views/vendors/sign_in.erb
<div class="container center">
    <div class="jumbotron">
      <form class="form-inline" role="form">
        <div class="form-group">
          <label class="sr-only" for="exampleInputEmail2">Email address</label>
          <input type="email" class="form-control" id="exampleInputEmail2" placeholder="Enter email">
        </div>
        <div class="form-group">
          <label class="sr-only" for="exampleInputPassword2">Password</label>
          <input type="password" class="form-control" id="exampleInputPassword2" placeholder="Password">
        </div>
        <div class="checkbox">
          <label>
            <input type="checkbox"> Remember me
          </label>
        </div>
        <button type="submit" class="btn btn-default">Sign in</button>
      </form>
    </div>
</div>