config/routes.rb
Dbproject::Application.routes.draw do
  get "static_pages/home"
  get "static_pages/help"

  resources :sessions, only: [:new, :create, :destroy]

  resources :vendors

  resources :carts

  resources :products

  resources :wishlists

  resources :customers

  root 'static_pages#home'

  match '/customer_signup', to: 'customers#new', via: 'get'
  match '/vendor_signup', to: 'vendors#new',  via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/add_to_cart', to: 'carts#add_to_cart', via: 'get'
  match '/remove_from_cart', to: 'carts#remove_from_cart', via: 'get'
  match '/product_listing', to: 'vendors#product_listing', via: 'get'
  match '/new_product_listing', to: 'vendors#new_product_listing', via: 'get'
  match '/add_random_product', to: 'vendors#add_random_product', via: 'get'

end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
  belongs_to :customer
  has_and_belongs_to_many :products
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_action :set_wishlist, only: [:show, :edit, :update, :destroy]

  def add_to_wishlist
    @wishlist = Wishlist.find_by(id:params[:wishlist_id])
    if params[:product_id]
      @product = Product.find_by(id:params[:product_id])
      @wishlist.products << @product
    end
    @wishlist.update_wishlist
    render 'show', :wishlist_id => @wishlist.id
  end

  def remove_from_wishlist
    @wishlist = Wishlist.find_by(id:params[:wishlist_id])
    if params[:product_id]
      @product = Product.find_by(id:params[:product_id])
      @wishlist.products.delete(@product)
    end
    @wishlist.update_cart
    render 'show', :wishlist_id => @wishlist.id
  end

  # GET /wishlists
  # GET /wishlists.json
  def index
    @wishlists = Wishlist.all
  end

  # GET /wishlists/1
  # GET /wishlists/1.json
  def show
  end

  # GET /wishlists/new
  def new
    @wishlist = Wishlist.new
  end

  # GET /wishlists/1/edit
  def edit
  end

  # POST /wishlists
  # POST /wishlists.json
  def create
    @wishlist = Wishlist.new(wishlist_params)

    respond_to do |format|
      if @wishlist.save
        format.html { redirect_to @wishlist, notice: 'Wishlist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @wishlist }
      else
        format.html { render action: 'new' }
        format.json { render json: @wishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wishlists/1
  # PATCH/PUT /wishlists/1.json
  def update
    respond_to do |format|
      if @wishlist.update(wishlist_params)
        format.html { redirect_to @wishlist, notice: 'Wishlist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @wishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wishlists/1
  # DELETE /wishlists/1.json
  def destroy
    @wishlist.destroy
    respond_to do |format|
      format.html { redirect_to wishlists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wishlist
      @wishlist = Wishlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wishlist_params
      params.require(:wishlist).permit(:title, :customer_id, :number_of_products, :created_at, :updated_at)
    end
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/wishlists/_form.html.erb
<%= form_for(@wishlist) do |f| %>
  <% if @wishlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wishlist.errors.count, "error") %> prohibited this wishlist from being saved:</h2>

      <ul>
      <% @wishlist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.number_field :customer_id %>
  </div>
  <div class="field">
    <%= f.label :number_of_products %><br>
    <%= f.number_field :number_of_products %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br>
    <%= f.datetime_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :updated_at %><br>
    <%= f.datetime_select :updated_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wishlists/edit.html.erb
<h1>Editing wishlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @wishlist %> |
<%= link_to 'Back', wishlists_path %>

app/views/wishlists/index.html.erb
<h1>Listing wishlists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Customer</th>
      <th>Number of products</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @wishlists.each do |wishlist| %>
      <tr>
        <td><%= wishlist.title %></td>
        <td><%= wishlist.customer_id %></td>
        <td><%= wishlist.number_of_products %></td>
        <td><%= wishlist.created_at %></td>
        <td><%= wishlist.updated_at %></td>
        <td><%= link_to 'Show', wishlist %></td>
        <td><%= link_to 'Edit', edit_wishlist_path(wishlist) %></td>
        <td><%= link_to 'Destroy', wishlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wishlist', new_wishlist_path %>

app/views/wishlists/new.html.erb
<h1>New wishlist</h1>

<%= render 'form' %>

<%= link_to 'Back', wishlists_path %>

app/views/wishlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @wishlist.title %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @wishlist.customer_id %>
</p>

<p>
  <strong>Number of products:</strong>
  <%= @wishlist.number_of_products %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @wishlist.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @wishlist.updated_at %>
</p>

<%= link_to 'Edit', edit_wishlist_path(@wishlist) %> |
<%= link_to 'Back', wishlists_path %>