config/routes.rb
Dbproject::Application.routes.draw do
  get "static_pages/home"
  get "static_pages/help"

  resources :sessions, only: [:new, :create, :destroy]

  resources :vendors

  resources :carts

  resources :products

  resources :wishlists

  resources :customers

  root 'static_pages#home'

  match '/customer_signup', to: 'customers#new', via: 'get'
  match '/vendor_signup', to: 'vendors#new',  via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/add_to_cart', to: 'carts#add_to_cart', via: 'get'
  match '/remove_from_cart', to: 'carts#remove_from_cart', via: 'get'
  match '/product_listing', to: 'vendors#product_listing', via: 'get'
  match '/new_product_listing', to: 'vendors#new_product_listing', via: 'get'
  match '/add_random_product', to: 'vendors#add_random_product', via: 'get'

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :vendor
  has_and_belongs_to_many :carts
  has_and_belongs_to_many :wishlists
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @cart = params[:cart]
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @vendor = Vendor.find_by(@product.vendor_id)
  end

  # GET /products/new
  def new
    @product = Product.new
    @vendor = Vendor.find_by(:id => params[:vendor_id])
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @vendor = Vendor.find_by(params[:product][:vendor_id])
    @vendor.products << @product
    respond_to do |format|
      if @product.save
        @vendor = Vendor.find_by(params[:vendor_id])
        @vendor.products << @product
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :stock, :created_at, :updated_at)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <form role="form">
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class:'form-control', placeholder:'Enter product name' %>
      </div>
      <div class="form-group">
        <%= f.label :price %>
        <%= f.text_field :price, class:'form-control', placeholder:'Enter price ($)' %>
      </div>
      <div class="form-group">
        <%= f.label :stock %>
        <%= f.text_field :stock, class:'form-control', placeholder:'Enter quantity you want to sell' %>
      </div>
      <div class="form-group" hidden="YES">
        <%= f.label :vendor_id %>
        <%= f.number_field :vendor_id, class:'form-control', placeholder:'bleh', :value => @vendor.id %>
      </div>
      <button type="submit" class="btn btn-default actions">Post Listing</button>
    </form>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="container center">
    <div class="jumbotron">
        <table class="table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Price</th>
              <th>Stock</th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <% @products.each do |product| %>
              <tr>
                <td><%= link_to product.name, product %></td>
                <td><%= "$%.2f" % product.price %></td>
                <td><%= product.stock %></td>
                <td><%= link_to 'Add To Cart', add_to_cart_path(:cart_id => @cart,:product_id => product.id) %></td>
                <td><%= link_to 'Add To Wishlist', edit_product_path(product) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
</div>
<br>

app/views/products/new.html.erb
<div class="container center">
  <div class="jumbotron">
    <p id="notice"><%= notice %></p>
    <%= render 'form' %>
  </div>
</div>

app/views/products/show.html.erb
<div class="container center">
  <div class="jumbotron">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Name:</strong>
      <%= @product.name %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= "$%.2f" % @product.price %>
    </p>

    <p>
      <strong>Quantity:</strong>
      <%= @product.stock %>
    </p>

    <p>
      <strong>Sold By:</strong>
      <%= link_to @vendor.username, @vendor %>
    </p>

    <%= link_to 'Back to Product Listing', Product, class:'btn btn-default btn-large' %>
  </div>
</div>